/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dannpa.asetapp.view;

import com.dannpa.asetapp.model.JenisAset;
import com.dannpa.asetapp.model.JenisTableModel;
import com.dannpa.asetapp.model.KategoriAset;
import com.dannpa.asetapp.model.KategoriTableModel;
import com.dannpa.asetapp.model.KondisiAset;
import com.dannpa.asetapp.model.KondisiTableModel;
import com.dannpa.asetapp.model.LokasiAset;
import com.dannpa.asetapp.model.LokasiTableModel;
import com.dannpa.asetapp.model.Role;
import com.dannpa.asetapp.model.RoleTableModel;
import com.dannpa.asetapp.model.User;
import com.dannpa.asetapp.model.UserTableModel;
import com.dannpa.asetapp.observable.AllAsetObservable;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.List;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author dannp
 */
public class ChoosableForm extends javax.swing.JFrame {

    AbstractTableModel theTableModel;

    final AllAsetObservable observable = new AllAsetObservable();

    /**
     * Creates new form ChoosableForm
     *
     * @param theTableModel
     */
    public ChoosableForm() {
    }

    public ChoosableForm(AbstractTableModel theTableModel, UtamaForm utama) {
        this.theTableModel = theTableModel;
        this.observable.addObserver(utama);
        initComponents();
        setSelectionListener();

    }

    public void setSelectionListener() {
        Class table = theTableModel.getClass();
        this.jTable2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                if (e.getClickCount() == 2) {
                    if (table.equals(JenisTableModel.class)) {
                        JenisTableModel theModel = (JenisTableModel) jTable2.getModel();

                        List<JenisAset> listJenis = theModel.getListJenisAset();
                        JenisAset jenisAset = listJenis.get(jTable2.getSelectedRow());

                        observable.changeData(jenisAset);
                    }
                    if (table.equals(KategoriTableModel.class)) {
                        KategoriTableModel theModel = (KategoriTableModel) jTable2.getModel();

                        List<KategoriAset> listJenis = theModel.getListKategoriAset();
                        KategoriAset kategoriAset = listJenis.get(jTable2.getSelectedRow());

                        observable.changeData(kategoriAset);
                    }
                    if (table.equals(KondisiTableModel.class)) {
                        KondisiTableModel theModel = (KondisiTableModel) jTable2.getModel();

                        List<KondisiAset> listKondisi = theModel.getListKondisiAset();
                        KondisiAset kondisiAset = listKondisi.get(jTable2.getSelectedRow());

                        observable.changeData(kondisiAset);
                    }
                    if (table.equals(LokasiTableModel.class)) {
                        LokasiTableModel theModel = (LokasiTableModel) jTable2.getModel();

                        List<LokasiAset> listLokasi = theModel.getListLokasiAset();
                        LokasiAset lokasiAset = listLokasi.get(jTable2.getSelectedRow());

                        observable.changeData(lokasiAset);
                    }//            System.out.println(jenisAset.getNamaJenisAset());
                    
                    if(table.equals(RoleTableModel.class)){
                        RoleTableModel theModel = (RoleTableModel) jTable2.getModel();
                        
                        List<Role> listRole = theModel.getListRole();
                        Role role = listRole.get(jTable2.getSelectedRow());
                        
                        observable.changeData(role);
                    }
                    ChoosableForm.this.dispose();
                }
            }

        });
//        this.jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            @Override
//            public void valueChanged(ListSelectionEvent e) {
//                
//                
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cari Berdasarkan Nama");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setModel(theTableModel);
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChoosableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChoosableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChoosableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChoosableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChoosableForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
