/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dannpa.asetapp.view;

import com.dannpa.asetapp.controller.AlokasiController;
import com.dannpa.asetapp.controller.AsetController;
import com.dannpa.asetapp.controller.JenisController;
import com.dannpa.asetapp.controller.KategoriController;
import com.dannpa.asetapp.controller.KondisiController;
import com.dannpa.asetapp.controller.LokasiController;
import com.dannpa.asetapp.controller.RoleController;
import com.dannpa.asetapp.controller.UserController;
import com.dannpa.asetapp.model.AlokasiAset;
import com.dannpa.asetapp.model.Aset;
import com.dannpa.asetapp.model.AsetTableModel;
import com.dannpa.asetapp.model.JenisAset;
import com.dannpa.asetapp.model.JenisTableModel;
import com.dannpa.asetapp.model.KategoriAset;
import com.dannpa.asetapp.model.KategoriTableModel;
import com.dannpa.asetapp.model.KondisiAset;
import com.dannpa.asetapp.model.KondisiTableModel;
import com.dannpa.asetapp.model.LokasiAset;
import com.dannpa.asetapp.model.LokasiTableModel;
import com.dannpa.asetapp.model.PenyusutanAset;
import com.dannpa.asetapp.model.Role;
import com.dannpa.asetapp.model.User;
import com.dannpa.asetapp.model.UserSession;
import com.dannpa.asetapp.model.UserTableModel;
import com.dannpa.asetapp.utils.ImageUtils;
import java.awt.CardLayout;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author dannp
 */
public class UtamaForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form UtamaForm
     */
    CardLayout layout;
    boolean beranda, aset, lokasi, kategori, kondisi, jenis, penyusutan, pengguna;

    ImageUtils utils;
    ImageIcon icon;
    ApplicationContext context = new ClassPathXmlApplicationContext("config-spring.xml");

    String panel[] = new String[2];

    boolean table;

    Aset _aset = null;
    JenisAset jenisAset = null;
    KategoriAset kategoriAset = null;
    KondisiAset kondisiAset = null;
    LokasiAset lokasiAset = null;
    User userModel = null;
    Role role = null;

    
    User user = UserSession.getUser();
    

    public UtamaForm() {

        initComponents();

        table = true;
        beranda = true;

        if (beranda) {
            setDisableAllButton();
        }
        this.setLocationRelativeTo(null);
        layout = (CardLayout) panelCard.getLayout();
        panel[0] = "cardFormBeranda";

        layout.show(panelCard, panel[0]);
        
        setFeaturePrivileges();

    }

    void setFeaturePrivileges() {
        switch (user.getRole().getId()) {
            case 1:
                // admin
                btnBeranda.setEnabled(false);
                btnAset.setEnabled(false);
                btnLokasi.setEnabled(false);
                btnKategori.setEnabled(false);
                btnKondisi.setEnabled(false);
                btnJenis.setEnabled(false);
                btnPengguna.setEnabled(true);
                break;
            case 2:
                // kepsek
                btnBeranda.setEnabled(true);
                btnAset.setEnabled(false);
                btnLokasi.setEnabled(false);
                btnKategori.setEnabled(false);
                btnKondisi.setEnabled(false);
                btnJenis.setEnabled(false);
                btnPengguna.setEnabled(true);
                break;
            case 3:
                // staff
                btnBeranda.setEnabled(false);
                btnAset.setEnabled(true);
                btnLokasi.setEnabled(true);
                btnKategori.setEnabled(true);
                btnKondisi.setEnabled(true);
                btnJenis.setEnabled(true);
                btnPengguna.setEnabled(false);
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        panelNavigasi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JButton();
        btnAset = new javax.swing.JButton();
        btnLokasi = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnKondisi = new javax.swing.JButton();
        btnJenis = new javax.swing.JButton();
        btnPengguna = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelUtama = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnUndo = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        btnCopyRecord = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSaveRecord = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnOpenDetail = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        panelPicker = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panelCard = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelFormRuangan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtLokasiKode = new javax.swing.JTextField();
        txtLokasiNama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panelFormAset = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAsetKode = new javax.swing.JTextField();
        txtAsetJenis = new javax.swing.JTextField();
        txtAsetNama = new javax.swing.JTextField();
        txtAsetKategori = new javax.swing.JTextField();
        txtAsetPemakaian = new javax.swing.JTextField();
        txtAsetNilai = new javax.swing.JTextField();
        txtAsetLokasi = new javax.swing.JTextField();
        txtAsetJumlah = new javax.swing.JTextField();
        txtAsetKondisi = new javax.swing.JTextField();
        dateChooserTglTerima = new com.toedter.calendar.JDateChooser();
        btnOptJenis = new javax.swing.JButton();
        btnOptKategori = new javax.swing.JButton();
        btnOptLokasi = new javax.swing.JButton();
        btnOptKondisi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtAsetUmurEkonomis = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtAsetPenyusutan = new javax.swing.JTextField();
        panelFormKondisi = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtKondisiKode = new javax.swing.JTextField();
        txtKondisiNama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        panelFormJenis = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtJenisKode = new javax.swing.JTextField();
        txtJenisNama = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        panelFormKategori = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtKategoriKode = new javax.swing.JTextField();
        txtKategoriNama = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        panelBeranda = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelPengguna = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        btnOptRole = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventarisasi App");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panelNavigasi.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        utils = new ImageUtils(getClass());
        icon = utils.createImageIcon("/resource/img/beranda.png", 20,20);

        btnBeranda.setIcon(icon);
        btnBeranda.setText("Beranda");
        btnBeranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnBeranda, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/barang.png", 20,20);
        btnAset.setIcon(icon);
        btnAset.setText("Aset");
        btnAset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnAset, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/ruangan.png", 20,20);
        btnLokasi.setIcon(icon);
        btnLokasi.setText("Lokasi Aset");
        btnLokasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLokasiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnLokasi, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/kategori.png", 20,20);
        btnKategori.setIcon(icon);
        btnKategori.setText("Kategori Aset");
        btnKategori.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnKategori, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/kondisi.png", 20,20);
        btnKondisi.setIcon(icon);
        btnKondisi.setText("Kondisi Aset");
        btnKondisi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKondisiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnKondisi, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/jenis.png", 20,20);
        btnJenis.setIcon(icon);
        btnJenis.setText("Jenis Aset");
        btnJenis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnJenis, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/users.png", 20,20);
        btnPengguna.setIcon(icon);
        btnPengguna.setText("Pengguna");
        btnPengguna.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenggunaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnPengguna, gridBagConstraints);

        icon = utils.createImageIcon("/resource/img/logout.png", 20,20);
        btnLogout.setIcon(icon);
        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(btnLogout, gridBagConstraints);

        panelNavigasi.add(jPanel3, java.awt.BorderLayout.NORTH);

        jSplitPane1.setLeftComponent(panelNavigasi);

        panelUtama.setLayout(new java.awt.BorderLayout());

        panelMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        utils = new ImageUtils(getClass());
        icon = utils.createImageIcon("/resource/img/undo.png", 20,20);
        btnUndo.setToolTipText("Undo");
        btnUndo.setMargin(new Insets(0,0,0,0));
        btnUndo.setIcon(icon);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        panelMenu.add(btnUndo);

        icon = utils.createImageIcon("/resource/img/insert.png", 20,20);
        btnNewRecord.setIcon(icon);
        btnNewRecord.setToolTipText("New Record");
        btnNewRecord.setMargin(new Insets(0,0,0,0));
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });
        panelMenu.add(btnNewRecord);

        icon = utils.createImageIcon("/resource/img/copy.png", 20,20);
        btnCopyRecord.setIcon(icon);
        btnCopyRecord.setToolTipText("Copy Record");
        btnCopyRecord.setMargin(new Insets(0,0,0,0));
        btnCopyRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyRecordActionPerformed(evt);
            }
        });
        panelMenu.add(btnCopyRecord);

        icon = utils.createImageIcon("/resource/img/delete.png", 20,20);
        btnDelete.setIcon(icon);
        btnDelete.setToolTipText("Delete");
        btnDelete.setMargin(new Insets(0,0,0,0));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelMenu.add(btnDelete);

        icon = utils.createImageIcon("/resource/img/save.png", 20,20);
        btnSaveRecord.setIcon(icon);
        btnSaveRecord.setToolTipText("Save Record");
        btnSaveRecord.setMargin(new Insets(0,0,0,0));
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });
        panelMenu.add(btnSaveRecord);

        icon = utils.createImageIcon("/resource/img/refresh.png", 20,20);
        btnRefresh.setIcon(icon);
        btnRefresh.setToolTipText("Refresh");
        btnRefresh.setMargin(new Insets(0,0,0,0));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        panelMenu.add(btnRefresh);

        icon = utils.createImageIcon("/resource/img/list.png", 20,20);
        btnOpenDetail.setIcon(icon);
        btnOpenDetail.setToolTipText("Open Detail");
        btnOpenDetail.setMargin(new Insets(0,0,0,0));
        btnOpenDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDetailActionPerformed(evt);
            }
        });
        panelMenu.add(btnOpenDetail);

        icon = utils.createImageIcon("/resource/img/close.png", 20,20);
        btnClose.setIcon(icon);
        btnClose.setToolTipText("Close");
        btnClose.setMargin(new Insets(0,0,0,0));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        panelMenu.add(btnClose);

        panelUtama.add(panelMenu, java.awt.BorderLayout.NORTH);

        panelPicker.setLayout(new java.awt.BorderLayout());
        panelPicker.add(jSeparator2, java.awt.BorderLayout.NORTH);

        panelCard.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
        );

        panelCard.add(panelTable, "cardTableAset");

        jLabel13.setText("Kode Lokasi");

        jLabel14.setText("Nama Lokasi");

        javax.swing.GroupLayout panelFormRuanganLayout = new javax.swing.GroupLayout(panelFormRuangan);
        panelFormRuangan.setLayout(panelFormRuanganLayout);
        panelFormRuanganLayout.setHorizontalGroup(
            panelFormRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(45, 45, 45)
                .addGroup(panelFormRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLokasiKode, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(txtLokasiNama))
                .addContainerGap())
        );
        panelFormRuanganLayout.setVerticalGroup(
            panelFormRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormRuanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtLokasiKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormRuanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtLokasiNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(489, Short.MAX_VALUE))
        );

        panelCard.add(panelFormRuangan, "cardFormRuangan");

        jLabel1.setText("Kode");

        jLabel2.setText("Nama Aset");

        jLabel3.setText("Jenis Aset");

        jLabel4.setText("Kategori Aset");

        jLabel5.setText("Tanggal Terima");

        jLabel6.setText("Pemakaian");

        jLabel7.setText("Nilai Aset");

        jLabel8.setText("Lokasi Aset");

        jLabel9.setText("Kondisi Barang");

        jLabel10.setText("Jumlah");

        txtAsetJenis.setEditable(false);

        txtAsetKategori.setEditable(false);

        txtAsetLokasi.setEditable(false);

        txtAsetKondisi.setEditable(false);

        dateChooserTglTerima.setDateFormatString("dd-MM-yyyy");

        btnOptJenis.setText("t");
        btnOptJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptJenisActionPerformed(evt);
            }
        });

        btnOptKategori.setText("t");
        btnOptKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptKategoriActionPerformed(evt);
            }
        });

        btnOptLokasi.setText("t");
        btnOptLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptLokasiActionPerformed(evt);
            }
        });

        btnOptKondisi.setText("t");
        btnOptKondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptKondisiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Penyusutan Aset");

        jLabel21.setText("Umur Ekonomis");

        txtAsetUmurEkonomis.setEditable(false);

        jLabel22.setText("Jumlah Penyusutan");

        txtAsetPenyusutan.setEditable(false);

        javax.swing.GroupLayout panelFormAsetLayout = new javax.swing.GroupLayout(panelFormAset);
        panelFormAset.setLayout(panelFormAsetLayout);
        panelFormAsetLayout.setHorizontalGroup(
            panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelFormAsetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                        .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsetJumlah)
                            .addGroup(panelFormAsetLayout.createSequentialGroup()
                                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                                        .addComponent(txtAsetLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnOptLokasi))
                                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                                        .addComponent(txtAsetKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnOptKondisi))
                                    .addComponent(dateChooserTglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                                        .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtAsetKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(txtAsetJenis))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnOptJenis)
                                            .addComponent(btnOptKategori))))
                                .addGap(493, 516, Short.MAX_VALUE))
                            .addComponent(txtAsetKode)
                            .addComponent(txtAsetNama)
                            .addComponent(txtAsetPemakaian)
                            .addComponent(txtAsetNilai)))
                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(32, 32, 32)
                        .addComponent(txtAsetUmurEkonomis))
                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFormAsetLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAsetPenyusutan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormAsetLayout.setVerticalGroup(
            panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormAsetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAsetKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnOptJenis))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnOptKategori))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooserTglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOptLokasi)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOptKondisi)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtAsetUmurEkonomis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormAsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsetPenyusutan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelCard.add(panelFormAset, "cardFormAset");

        jLabel15.setText("Kode Kondisi");

        jLabel16.setText("Nama Kondisi");

        javax.swing.GroupLayout panelFormKondisiLayout = new javax.swing.GroupLayout(panelFormKondisi);
        panelFormKondisi.setLayout(panelFormKondisiLayout);
        panelFormKondisiLayout.setHorizontalGroup(
            panelFormKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormKondisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(41, 41, 41)
                .addGroup(panelFormKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKondisiNama, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(txtKondisiKode))
                .addContainerGap())
        );
        panelFormKondisiLayout.setVerticalGroup(
            panelFormKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormKondisiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtKondisiKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtKondisiNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(489, Short.MAX_VALUE))
        );

        panelCard.add(panelFormKondisi, "cardFormKondisi");

        jLabel17.setText("Kode Jenis");

        jLabel18.setText("Nama Jenis");

        javax.swing.GroupLayout panelFormJenisLayout = new javax.swing.GroupLayout(panelFormJenis);
        panelFormJenis.setLayout(panelFormJenisLayout);
        panelFormJenisLayout.setHorizontalGroup(
            panelFormJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(52, 52, 52)
                .addGroup(panelFormJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJenisNama, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(txtJenisKode))
                .addContainerGap())
        );
        panelFormJenisLayout.setVerticalGroup(
            panelFormJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtJenisKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtJenisNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(489, Short.MAX_VALUE))
        );

        panelCard.add(panelFormJenis, "cardFormJenis");

        jLabel19.setText("Kode Kategori");

        jLabel20.setText("Nama Kategori");

        javax.swing.GroupLayout panelFormKategoriLayout = new javax.swing.GroupLayout(panelFormKategori);
        panelFormKategori.setLayout(panelFormKategoriLayout);
        panelFormKategoriLayout.setHorizontalGroup(
            panelFormKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(35, 35, 35)
                .addGroup(panelFormKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKategoriNama, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(txtKategoriKode))
                .addContainerGap())
        );
        panelFormKategoriLayout.setVerticalGroup(
            panelFormKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtKategoriKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtKategoriNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(489, Short.MAX_VALUE))
        );

        panelCard.add(panelFormKategori, "cardFormKategori");

        jLabel11.setText("beranda");

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel11)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel11)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        panelCard.add(panelBeranda, "cardFormBeranda");

        jLabel23.setText("Username");

        jLabel24.setText("Password");

        jLabel25.setText("Role");

        txtRole.setEditable(false);

        btnOptRole.setText("t");
        btnOptRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPenggunaLayout = new javax.swing.GroupLayout(panelPengguna);
        panelPengguna.setLayout(panelPenggunaLayout);
        panelPenggunaLayout.setHorizontalGroup(
            panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPenggunaLayout.createSequentialGroup()
                        .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(52, 52, 52)
                        .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                            .addComponent(txtUsername)))
                    .addGroup(panelPenggunaLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOptRole)
                        .addGap(491, 491, 491)))
                .addContainerGap())
        );
        panelPenggunaLayout.setVerticalGroup(
            panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(btnOptRole))
                .addContainerGap(439, Short.MAX_VALUE))
        );

        panelCard.add(panelPengguna, "cardFormPengguna");

        panelPicker.add(panelCard, java.awt.BorderLayout.CENTER);

        panelUtama.add(panelPicker, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(panelUtama);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        normalState();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
        // TODO add your handling code here:
        layout.show(panelCard, panel[0]);

        if (aset) {
            clearAllOfAset();
        }

        if (jenis) {
            clearAllOfJenis();

        }

        if (kondisi) {
            clearAllOfKondisi();

        }

        if (kategori) {
            clearAllOfKategori();

        }

        newRecordState();

        table = true;

    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed


    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed
        // TODO add your handling code here:
        AsetController asetController = new AsetController(context);
        JenisController jenisController = new JenisController(context);
        KategoriController kategoriController = new KategoriController(context);
        KondisiController kondisiController = new KondisiController(context);
        AlokasiController alokasiController = new AlokasiController(context);
        LokasiController lokasiController = new LokasiController(context);
        UserController userController = new UserController(context);

        if (aset) {
            String kodeAset = txtAsetKode.getText();
            String namaAset = txtAsetNama.getText();
            int pemakaian = Integer.parseInt(txtAsetPemakaian.getText().length() > 0 ? txtAsetPemakaian.getText() : "0");
            int jumlah = Integer.parseInt(txtAsetJumlah.getText().length() > 0 ? txtAsetJumlah.getText() : "0");
            double nilai = Double.parseDouble(txtAsetNilai.getText().length() > 0 ? txtAsetNilai.getText() : "0");
            long tglTerima = dateChooserTglTerima.getCalendar().getTimeInMillis();

            Aset aset = new Aset();
            aset.setKodeAset(kodeAset);
            aset.setNamaAset(namaAset);
            aset.setPemakaian(pemakaian);
            aset.setJumlahAset(jumlah);
            aset.setTglTerimaAset(tglTerima);
            aset.setNilaiAset(nilai);
            aset.setJenisAset(jenisAset);
            aset.setKondisiAset(kondisiAset);
            aset.setKategoriAset(kategoriAset);
            if (penyusutan) {
                int umurEkonomis = Integer.parseInt(txtAsetUmurEkonomis.getText());
                double nilaiPenyusutan = Double.parseDouble(txtAsetPenyusutan.getText());
                PenyusutanAset penyusutan = new PenyusutanAset();

                penyusutan.setUmurEkonomis(umurEkonomis);
                penyusutan.setJumlahPenyusutan(nilaiPenyusutan);

                aset.setPenyusutanAset(penyusutan);
                asetController.insertAset(aset);
            } else {
                asetController.insertAset(aset);

                AlokasiAset alokasiAset = new AlokasiAset();
                alokasiAset.setAset(aset);
                alokasiAset.setLokasi(lokasiAset);
//            alokasiAset.setLokasi(lokasiAset);

                alokasiController.insert(alokasiAset);

            }

            clearAllOfAset();

        }

        if (jenis) {
            String kodeJenis = txtJenisKode.getText();
            String namaJenis = txtJenisNama.getText();

            JenisAset jenisAset = new JenisAset();
            jenisAset.setKodeJenisAset(kodeJenis);
            jenisAset.setNamaJenisAset(namaJenis);

            jenisController.insertAset(jenisAset);

            clearAllOfJenis();
        }

        if (kondisi) {
            String kodeKondisi = txtKondisiKode.getText();
            String namaKondisi = txtKondisiNama.getText();

            KondisiAset kondisiAset = new KondisiAset();
            kondisiAset.setKodeKondisiAset(kodeKondisi);
            kondisiAset.setNamaKondisiAset(namaKondisi);

            kondisiController.insert(kondisiAset);

            clearAllOfKondisi();

        }

        if (kategori) {
            String kodeKategori = txtKategoriKode.getText();
            String namaKategori = txtKategoriNama.getText();

            KategoriAset kategoriAset = new KategoriAset();
            kategoriAset.setKodeKategoriAset(kodeKategori);
            kategoriAset.setNamaKategoriAset(namaKategori);

            kategoriController.insert(kategoriAset);
            clearAllOfKategori();
        }

        if (lokasi) {
            String kodeLokasi = txtLokasiKode.getText();
            String namaLokasi = txtLokasiNama.getText();

            LokasiAset lokasiAset = new LokasiAset();
            lokasiAset.setKodeLokasiAset(kodeLokasi);
            lokasiAset.setNamaLokasiAset(namaLokasi);

            lokasiController.insert(lokasiAset);

            clearAllOfLokasi();
        }
        
        if(pengguna){
            String username = txtUsername.getText();
            String password = txtPassword.getText();
            
            User user = new User();
            user.setUsername(username);
            user.setPassword(password);
            user.setRole(role);
            
            userController.insert(user);
            
            clearAllOfUser();
            
            
        }

        normalState();


    }//GEN-LAST:event_btnSaveRecordActionPerformed

    private void btnAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsetActionPerformed
        // TODO add your handling code here:

        beranda = false;
        aset = true;
        lokasi = false;
        kategori = false;
        kondisi = false;
        jenis = false;
        penyusutan = false;
        pengguna  = false;

        panel[0] = "cardFormAset";
        panel[1] = "cardTableAset";
        layout.show(panelCard, panel[0]);
        table = true;
        normalState();
    }//GEN-LAST:event_btnAsetActionPerformed

    private void btnLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLokasiActionPerformed
        // TODO add your handling code here:
        beranda = false;
        aset = false;
        lokasi = true;
        kategori = false;
        kondisi = false;
        jenis = false;
        penyusutan = false;
        pengguna  = false;

        panel[0] = "cardFormRuangan";
        panel[1] = "cardTableAset";

        layout.show(panelCard, panel[0]);
        table = true;
        normalState();
    }//GEN-LAST:event_btnLokasiActionPerformed

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        beranda = true;
        aset = false;
        lokasi = false;
        kategori = false;
        kondisi = false;
        jenis = false;
        penyusutan = false;
        pengguna  = false;

        table = true;

        panel[0] = "cardFormBeranda";
        layout.show(panelCard, panel[0]);
        table = true;

        setDisableAllButton();

        System.out.println(user.toString());

    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        // TODO add your handling code here:
        beranda = false;
        aset = false;
        lokasi = false;
        kategori = true;
        kondisi = false;
        jenis = false;
        penyusutan = false;
        pengguna  = false;

        panel[0] = "cardFormKategori";
        panel[1] = "cardTableAset";

        // memunculkan panel kategori
        layout.show(panelCard, panel[0]);

        table = true;
        normalState();
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnKondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKondisiActionPerformed
        // TODO add your handling code here:

        beranda = false;
        aset = false;
        lokasi = false;
        kategori = false;
        kondisi = true;
        jenis = false;
        penyusutan = false;
        pengguna  = false;

        panel[0] = "cardFormKondisi";
        panel[1] = "cardTableAset";

        // memunculkan panel kondisi
        layout.show(panelCard, panel[0]);

        table = true;
        normalState();
    }//GEN-LAST:event_btnKondisiActionPerformed

    private void btnJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisActionPerformed
        // TODO add your handling code here:
        beranda = false;
        aset = false;
        lokasi = false;
        kategori = false;
        kondisi = false;
        jenis = true;
        penyusutan = false;
        pengguna  = false;

        panel[0] = "cardFormJenis";
        panel[1] = "cardTableAset";

        // memunculkan panel jenis
        layout.show(panelCard, panel[0]);

        table = true;
        normalState();
    }//GEN-LAST:event_btnJenisActionPerformed

    private void btnOptJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptJenisActionPerformed
        // TODO add your handling code here:
        JenisController controller = new JenisController(context);
        AbstractTableModel model = controller.selectAll();
        ChoosableForm form = new ChoosableForm(model, this);
        form.setVisible(true);
    }//GEN-LAST:event_btnOptJenisActionPerformed

    private void btnOptKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptKategoriActionPerformed
        // TODO add your handling code here:
        KategoriController controller = new KategoriController(context);
        AbstractTableModel model = controller.selectAll();
        ChoosableForm form = new ChoosableForm(model, this);
        form.setVisible(true);


    }//GEN-LAST:event_btnOptKategoriActionPerformed

    private void btnOptLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptLokasiActionPerformed
        // TODO add your handling code here:
        LokasiController controller = new LokasiController(context);
        AbstractTableModel model = controller.selectAll();
        ChoosableForm form = new ChoosableForm(model, this);
        form.setVisible(true);
    }//GEN-LAST:event_btnOptLokasiActionPerformed

    private void btnOpenDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDetailActionPerformed
        // TODO add your handling code here:
        if (!table) {
            layout.show(panelCard, panel[0]);

            table = true;

        } else {
            layout.show(panelCard, panel[1]);
            AbstractTableModel tableModel = null;

            if (aset) {
                AsetController controller = new AsetController(context);
                tableModel = controller.selectAll();
            }

            if (jenis) {
                JenisController controller = new JenisController(context);
                tableModel = controller.selectAll();
            }

            if (kategori) {

                KategoriController controller = new KategoriController(context);
                tableModel = controller.selectAll();

            }

            if (lokasi) {
                LokasiController controller = new LokasiController(context);
                tableModel = controller.selectAll();
            }

            if (kondisi) {
                KondisiController controller = new KondisiController(context);
                tableModel = controller.selectAll();
            }
            
            if (pengguna){
                UserController controller = new UserController(context);
                tableModel = controller.selectAll();
            }

            jTable1.setModel(tableModel);

            table = false;

        }

    }//GEN-LAST:event_btnOpenDetailActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        AsetController asetController = new AsetController(context);
        JenisController jenisController = new JenisController(context);
        KategoriController kategoriController = new KategoriController(context);
        KondisiController kondisiController = new KondisiController(context);
        AlokasiController alokasiController = new AlokasiController(context);
        LokasiController lokasiController = new LokasiController(context);
        UserController userController = new UserController(context);
        
        if(aset){
            asetController.deleteAset(_aset);
        }
        
        if(jenis){
            jenisController.deleteJenis(jenisAset);
            clearAllOfJenis();
            
        }
        
        if(kategori){
            kategoriController.deleteKategori(kategoriAset);
            clearAllOfKategori();
        }
        
        if(kondisi){
            kondisiController.deleteKondisi(kondisiAset);
            clearAllOfKondisi();
        }
        
        if(lokasi){
            lokasiController.deleteLokasi(lokasiAset);
            clearAllOfLokasi();
        }
        
        if(pengguna){
            userController.deleteUser(userModel);
            
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOptKondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptKondisiActionPerformed
        // TODO add your handling code here:
        KondisiController controller = new KondisiController(context);
        AbstractTableModel model = controller.selectAll();
        ChoosableForm form = new ChoosableForm(model, this);
        form.setVisible(true);
    }//GEN-LAST:event_btnOptKondisiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Class table = jTable1.getModel().getClass();
        if (evt.getClickCount() == 1) {
            if (table.equals(JenisTableModel.class)) {
                JenisTableModel theModel = (JenisTableModel) jTable1.getModel();

                List<JenisAset> listJenis = theModel.getListJenisAset();
                jenisAset = listJenis.get(jTable1.getSelectedRow());

                txtJenisKode.setText(jenisAset.getKodeJenisAset());
                txtJenisNama.setText(jenisAset.getNamaJenisAset());

            }
            if (table.equals(KategoriTableModel.class)) {
                KategoriTableModel theModel = (KategoriTableModel) jTable1.getModel();

                List<KategoriAset> listJenis = theModel.getListKategoriAset();
                kategoriAset = listJenis.get(jTable1.getSelectedRow());

                txtKategoriKode.setText(kategoriAset.getKodeKategoriAset());
                txtKategoriNama.setText(kategoriAset.getNamaKategoriAset());

            }
            if (table.equals(KondisiTableModel.class)) {
                KondisiTableModel theModel = (KondisiTableModel) jTable1.getModel();

                List<KondisiAset> listKondisi = theModel.getListKondisiAset();
                kondisiAset = listKondisi.get(jTable1.getSelectedRow());

                txtKondisiKode.setText(kondisiAset.getKodeKondisiAset());
                txtKondisiNama.setText(kondisiAset.getNamaKondisiAset());

            }
            if (table.equals(LokasiTableModel.class)) {
                LokasiTableModel theModel = (LokasiTableModel) jTable1.getModel();

                List<LokasiAset> listLokasi = theModel.getListLokasiAset();
                lokasiAset = listLokasi.get(jTable1.getSelectedRow());

                txtLokasiKode.setText(lokasiAset.getKodeLokasiAset());
                txtLokasiNama.setText(lokasiAset.getNamaLokasiAset());

            }//            System.out.println(jenisAset.getNamaJenisAset());

            if (table.equals(AsetTableModel.class)) {
                AsetTableModel theModel = (AsetTableModel) jTable1.getModel();

                List<Aset> listAset = theModel.getListAset();
                Aset aset = listAset.get(jTable1.getSelectedRow());
                _aset = listAset.get(jTable1.getSelectedRow());
                jenisAset = _aset.getJenisAset();
                kategoriAset = _aset.getKategoriAset();
                kondisiAset = _aset.getKondisiAset();
//                lokasiAset = listAset.get(jTable1.getSelectedRow()).getLokasi();

                txtAsetKode.setText(_aset.getKodeAset());
                txtAsetNama.setText(_aset.getNamaAset());
                txtAsetJenis.setText(jenisAset.getNamaJenisAset());
                txtAsetKategori.setText(kategoriAset.getNamaKategoriAset());

                txtAsetPemakaian.setText(String.valueOf(_aset.getPemakaian()));
                txtAsetNilai.setText(String.valueOf(_aset.getNilaiAset()));
                txtAsetLokasi.setText(lokasiAset.getNamaLokasiAset());

//                txtAsetJumlah.setText(String.valueOf(alokasiAset.getJumlahAlokasiAset()));

                txtAsetKondisi.setText(kondisiAset.getNamaKondisiAset());

            }
            
            if (table.equals(UserTableModel.class)) {
                UserTableModel theModel = (UserTableModel) jTable1.getModel();

                List<User> listUser = theModel.getListUser();
                userModel = listUser.get(jTable1.getSelectedRow());

                txtUsername.setText(userModel.getUsername());
                txtPassword.setText(userModel.getPassword());
                txtRole.setText(userModel.getRole().getRoleName());

            }//            System.out.println(jenisAset.getNamaJenisAset());

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenggunaActionPerformed
        // TODO add your handling code here:
        
        beranda = false;
        aset = false;
        lokasi = false;
        kategori = false;
        kondisi = false;
        jenis = false;
        penyusutan = false;
        pengguna  = true;

        panel[0] = "cardFormPengguna";
        panel[1] = "cardTableAset";

        // memunculkan panel jenis
        layout.show(panelCard, panel[0]);

        table = true;
        normalState();
    }//GEN-LAST:event_btnPenggunaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
        UserSession.clearUserSession();
        
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCopyRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopyRecordActionPerformed

    private void btnOptRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptRoleActionPerformed
        // TODO add your handling code here:
        RoleController controller = new RoleController(context);
        AbstractTableModel model = controller.selectAll();
        ChoosableForm form = new ChoosableForm(model, this);
        form.setVisible(true);
        
    }//GEN-LAST:event_btnOptRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtamaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAset;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCopyRecord;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnJenis;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnKondisi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLokasi;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnOpenDetail;
    private javax.swing.JButton btnOptJenis;
    private javax.swing.JButton btnOptKategori;
    private javax.swing.JButton btnOptKondisi;
    private javax.swing.JButton btnOptLokasi;
    private javax.swing.JButton btnOptRole;
    private javax.swing.JButton btnPengguna;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JButton btnUndo;
    private com.toedter.calendar.JDateChooser dateChooserTglTerima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelFormAset;
    private javax.swing.JPanel panelFormJenis;
    private javax.swing.JPanel panelFormKategori;
    private javax.swing.JPanel panelFormKondisi;
    private javax.swing.JPanel panelFormRuangan;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNavigasi;
    private javax.swing.JPanel panelPengguna;
    private javax.swing.JPanel panelPicker;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTextField txtAsetJenis;
    private javax.swing.JTextField txtAsetJumlah;
    private javax.swing.JTextField txtAsetKategori;
    private javax.swing.JTextField txtAsetKode;
    private javax.swing.JTextField txtAsetKondisi;
    private javax.swing.JTextField txtAsetLokasi;
    private javax.swing.JTextField txtAsetNama;
    private javax.swing.JTextField txtAsetNilai;
    private javax.swing.JTextField txtAsetPemakaian;
    private javax.swing.JTextField txtAsetPenyusutan;
    private javax.swing.JTextField txtAsetUmurEkonomis;
    private javax.swing.JTextField txtJenisKode;
    private javax.swing.JTextField txtJenisNama;
    private javax.swing.JTextField txtKategoriKode;
    private javax.swing.JTextField txtKategoriNama;
    private javax.swing.JTextField txtKondisiKode;
    private javax.swing.JTextField txtKondisiNama;
    private javax.swing.JTextField txtLokasiKode;
    private javax.swing.JTextField txtLokasiNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    void clearAllOfAset() {
        txtAsetJenis.setText("");
        txtAsetJumlah.setText("");
        txtAsetKategori.setText("");
        txtAsetKode.setText("");
        txtAsetKondisi.setText("");
        txtAsetLokasi.setText("");
        txtAsetNama.setText("");
        txtAsetNilai.setText("");
        txtAsetPemakaian.setText("");
        jenisAset = null;
        kategoriAset = null;
        kondisiAset = null;
        lokasiAset = null;
    }

    void disableAllAsetField() {
//        txtAsetJenis.setEnabled(false);
        txtAsetJumlah.setEditable(false);
//        txtAsetKategori.setEnabled(false);
        txtAsetKode.setEditable(false);
//        txtAsetKondisi.setEnabled(false);
//        txtAsetLokasi.setEnabled(false);
        txtAsetNama.setEditable(false);
        txtAsetNilai.setEditable(false);
        txtAsetPemakaian.setEditable(false);
        btnOptJenis.setEnabled(false);
        btnOptKondisi.setEnabled(false);
        btnOptKategori.setEnabled(false);
        btnOptLokasi.setEnabled(false);
    }

    void enableAsetField() {
//        txtAsetJenis.setEnabled(false);
        txtAsetJumlah.setEnabled(true);
//        txtAsetKategori.setEnabled(false);
        txtAsetKode.setEnabled(false);
//        txtAsetKondisi.setEnabled(false);
//        txtAsetLokasi.setEnabled(false);
        txtAsetNama.setEnabled(false);
        txtAsetNilai.setEnabled(false);
        txtAsetPemakaian.setEnabled(false);
        btnOptJenis.setEnabled(false);
        btnOptKondisi.setEnabled(false);
        btnOptKategori.setEnabled(false);
        btnOptLokasi.setEnabled(false);

    }

    void clearAllOfJenis() {
        txtJenisKode.setText("");
        txtJenisNama.setText("");
    }

    void clearAllOfKondisi() {
        txtKondisiKode.setText("");
        txtKondisiNama.setText("");
    }

    void clearAllOfKategori() {
        txtKategoriKode.setText("");
        txtKategoriNama.setText("");
    }

    void clearAllOfLokasi() {
        txtLokasiKode.setText("");
        txtLokasiNama.setText("");
    }
    
    void clearAllOfUser(){
        txtUsername.setText("");
        txtPassword.setText("");
        txtRole.setText("");
    }

    void setDisableAllButton() {
        btnUndo.setEnabled(false);
        btnNewRecord.setEnabled(false);
        btnCopyRecord.setEnabled(false);
        btnClose.setEnabled(false);
        btnDelete.setEnabled(false);
        btnOpenDetail.setEnabled(false);
        btnRefresh.setEnabled(false);
        btnSaveRecord.setEnabled(false);
    }

    void newRecordState() {
        btnUndo.setEnabled(true);
        btnCopyRecord.setEnabled(false);
        btnClose.setEnabled(true);
        btnNewRecord.setEnabled(false);
        btnDelete.setEnabled(false);
        btnOpenDetail.setEnabled(false);
        btnRefresh.setEnabled(false);
        btnSaveRecord.setEnabled(true);
    }

    void normalState() {
        btnUndo.setEnabled(false);
        btnCopyRecord.setEnabled(true);
        btnClose.setEnabled(true);
        btnNewRecord.setEnabled(true);
        btnDelete.setEnabled(true);
        btnOpenDetail.setEnabled(true);
        btnRefresh.setEnabled(true);
        btnSaveRecord.setEnabled(false);
    }

    @Override
    public void update(Observable o, Object arg) {

        Class asd = arg.getClass();

        if (JenisAset.class.equals(asd)) {
            System.out.println("jenis");
            jenisAset = (JenisAset) arg;
            txtAsetJenis.setText(((JenisAset) arg).getNamaJenisAset());

        }

        if (KategoriAset.class
                .equals(asd)) {
            System.out.println("kategori");
            kategoriAset = (KategoriAset) arg;
            txtAsetKategori.setText(((KategoriAset) arg).getNamaKategoriAset());
            if (kategoriAset.getNamaKategoriAset().equals("ASET TETAP")) {
                txtAsetUmurEkonomis.setEditable(true);
                txtAsetPenyusutan.setEditable(true);
                penyusutan = true;
            } else {
                txtAsetUmurEkonomis.setEditable(false);
                txtAsetPenyusutan.setEditable(false);
                penyusutan = false;
            }

        }

        if (KondisiAset.class
                .equals(asd)) {
            System.out.println("kondisi");
            kondisiAset = (KondisiAset) arg;
            txtAsetKondisi.setText(((KondisiAset) arg).getNamaKondisiAset());

        }

        if (LokasiAset.class
                .equals(asd)) {
            System.out.println("lokasi");
            lokasiAset = (LokasiAset) arg;
            txtAsetLokasi.setText(((LokasiAset) arg).getNamaLokasiAset());
        }
        
        if(Role.class.equals(asd)){
            System.out.println("role");
            role = (Role) arg;
            txtRole.setText((role.getRoleName()));
        }

    }

}
